name: mentis
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.0
  table_calendar: ^3.0.6
  flutter_rating_bar: ^4.0.0
  flutter_credit_card: ^4.0.1
#  firebase_core: ^2.24.2
#  cloud_firestore: ^4.14.0
#  firebase_auth: ^4.16.0
  awesome_dialog: ^3.0.2
  flutter_multiselect: ^1.0.0
  bloc: ^8.1.3
  smooth_page_indicator: ^1.1.0
  dio: ^5.4.0
  get_it: ^7.6.0
  go_router: ^10.0.0
  cupertino_icons: ^1.0.2
  pretty_dio_logger: ^1.3.1
  flutter_dotenv: ^5.1.0
  dartz: ^0.10.1
  rxdart: ^0.27.7
  shared_preferences: ^2.2.3
  logger:
  animate_do: ^3.3.4
  mqtt_client: ^10.2.1
  flutter_tts: ^4.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/
     - .env
